### PR TITLE
Update neo4j dependency

### LINKED ISSUE #262: [BUG] Relax neo4j dependency version
Currently gqlalchemy requires neo4j version 4.4.

In neo4j v5 they added async driver support that for us is crucial to achieve performance.

Unfortunately do the v4.4 dependency it's impossible to install both gqlalchemy and neo4j v5 into the same python environment (not without doing some ugly hacks).
I was wondering if that v4.4 version pin is really critical for something, or can it be updated/relaxed to a more general version maybe ">= 4.4"?

### PR DESCRIPTION
**Pull request by alex-linx**
### Description
Update the neo4j dependency to be more general, specifically to allow for using in conjuction with neo4j driver v5.

### Pull request type

- [X] Build or packaging related changes

### Related issues

Closes #262 

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

I tested it against a neo4j running in docker.
Running against neo4j v5.1 did break because the uniqueness keyword doesn't exist anymore in show indexes.
However the neo4j driver v5 is backward compatbile so when running the tests against neo4j docker v4.4 they pass

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

### CODE REVIEW

**Review by katarinasupe — APPROVED** [review]

**Review by antepusic — APPROVED** [review]

**Comment by katarinasupe** [comment]
Hi @alex-linx thank you for the contribution! The team will probably sync next week to agree on the next release. I will keep you updated.

**Comment by katarinasupe** [comment]
Please just remove trigger typing fix from here, so we have it at #260 :)

**Comment by alex-linx** [comment]
@katarinasupe Done

**Comment by katarinasupe** [comment]
Thank you @alex-linx for the contributions. We will work on the release at the end of the next week. Stay tuned :)

**Pull request merged**
