### PR TITLE
Add load node test

### PR DESCRIPTION
**Pull request by katarinasupe**
I added a test related to closed issue https://github.com/memgraph/gqlalchemy/issues/79.

### CODE REVIEW

**Comment by MasterMedo** [comment]
You mentioned the solution is not working for you, but these tests show that everything was executed correctly. The reason the tests are failing is because the files aren't formatted correctly. The linter and formatter fail the tests.

You should run flake8 and black before pushing (or use a draft PR).

**Comment by katarinasupe** [comment]
I have run flake8 and black, but locally I get this error:
`
FAILED tests/ogm/load_node_test.py::test_load_node - mgclient.DatabaseError: line 1:36 extraneous input 'node' expecting {<EOF>, ';'}`

**Comment by MasterMedo** [comment]
> I have run flake8 and black, but locally I get this error: ` FAILED tests/ogm/load_node_test.py::test_load_node - mgclient.DatabaseError: line 1:36 extraneous input 'node' expecting {<EOF>, ';'}`

You ran black and flake8 with poetry?
Did you run `poetry install` before that?
What version of pymgclient are you using?

**Comment by katarinasupe** [comment]
First I run poetry install, then flake8 and black with poetry. I don't have any problems with testing on other PR (https://github.com/memgraph/docs/pull/292), but here I keep getting the same error. I am using pymgclient 1.1.0.

**Comment by katarinasupe** [comment]
I added a test where I defined property without Field, and it's still being saved in Memgraph.

**Comment by MasterMedo** [comment]
I think this test shows a flaw with the way tsome tests were defined. Can you try renaming the test file to `test_load_node`? I think all test files should be starting with `test`. I probably broke that rule at some point but didn't notice it up until now because I always manually tested the files individually until they worked.

**Comment by katarinasupe** [comment]
`test_without_field` fails, as expected. 

We thought that if we define a class like this:

```
 class User(Node):
        name: str = Field(index=True, unique=True, db=memgraph)
        followers: int
```
        
that the `followers` property won't be saved into the database. This is wrong since `followers` property is saved in the database.

**Comment by katarinasupe** [comment]
Removed `test_without_field`, since we still don't have that feature. I'll add the test after implementing the feature in another PR.

**Review by g-despot — APPROVED** [review]

**Pull request merged**
