### PR TITLE
Align develop with main

### PR DESCRIPTION
**Pull request by imilinovic**
### Description

Align develop with main so the new PRs that will be merged to develop have normal history & files changed.

### Pull request type

Please delete options that are not relevant.
- [X] Other (please describe):

### Related issues

Delete section if this PR doesn't resolve any issues. 

Closes (link to issue)

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [gqlalchemy/docs](https://github.com/memgraph/gqlalchemy/tree/main/docs)

######################################

### CODE REVIEW

**Comment by as51340** [comment]
What are your commits? History seems messy

**Comment by imilinovic** [comment]
This is just a merge with main so the other PRs that will come after will be clean

**Review by katarinasupe — APPROVED** [review]

**Review by katarinasupe — COMMENTED** [review]
If I remembered correctly, I think we abandoned develop branch and continued with just merging to main and creating release branch after the release (https://github.com/memgraph/gqlalchemy/blob/main/CONTRIBUTING.md). @as51340 do you remember if that's what we concluded?

**Comment by katarinasupe** [comment]
No need to do this, we no longer use the develop branch. @imilinovic

**Pull request closed without merging**
