### PR TITLE
Add latest signatures

### PR DESCRIPTION
**Pull request by katarinasupe**
### Description

Updated procedures signatures to match the latest Memgraph. Skipped test for procedure signatures. Updated test for constraint to remove reserved keyword text in the latest Memgraph.

### Pull request type

Please delete options that are not relevant.

- [x] Bugfix

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [gqlalchemy/docs](https://github.com/memgraph/gqlalchemy/tree/main/docs)

######################################

### CODE REVIEW

**Comment by katarinasupe** [comment]
Added new signatures, but tests kept failing. I spoke shortly with @Josipmrden and the decision is to skip the test for now. This is not as important and it's blocking other features from being merged.

TODO: check fail on constraints test.

**Comment by katarinasupe** [comment]
@antepusic @as51340 @Josipmrden I will just need approval so I can merge after all tests pass

**Review by as51340 — APPROVED** [review]
LGTM

**Review by antepusic — APPROVED** [review]
All looks good!

**Pull request merged**
