### PR TITLE
Add parameters to execute methods

### PR DESCRIPTION
**Pull request by lcorcodilos**
### Description

The `mgclient` has support for accepting parameters with a query to execute. I added functionality so the Connection and DatabaseClient classes can accept these as well. 

### Pull request type

Please delete options that are not relevant.

- [X] Feature

### Checklist:

Honestly, I did this in 15 minutes to get something working for myself and wanted to share it. I felt this was better than submitting an issue since I had already done some work on it. I don't think this is terribly complicated but, to me, it's a core feature and so I think it would be better implemented by a regular maintainer who knows where the tests live, the style guidelines, etc.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

### CODE REVIEW

**Comment by lcorcodilos** [comment]
Properly based on `develop` now - sorry about that.

**Comment by Josipmrden** [comment]
@katarinasupe  this looks good, but we'll need at least one test for this

**Comment by katarinasupe** [comment]
@Josipmrden let's merge this to develop and create a new PR for tests. @lcorcodilos thank you for the contribution! Since you are using this, feel free to provide us with an example usage for quicker test writing :D

**Comment by katarinasupe** [comment]
@lcorcodilos can you run black and flake8 checks?

**Comment by katarinasupe** [comment]
Hi @lcorcodilos :D 
I tested your PR locally too. You probably get connection errors because there has to be a Neo4j instance running for all tests to pass. Locally, all is fine for me too. All in all, I think we can merge this do `develop` @Josipmrden ✅ 

Awesome to hear you managed to lower your import time from 9 hours to 20 minutes. Great example of good database usage! 😄 And, of course, there is interest - always! I see you linked your website to GitHub, so I'll contact you via email. We can hop on a call to talk about your use case and if you need anything.

@antoniofilipovic, you might find reported memory issue helpful input!

Thank you, @lcorcodilos, for sharing this 😄

**Review by katarinasupe — APPROVED** [review]

**Review by Josipmrden — APPROVED** [review]

**Comment by vpavicic** [comment]
@brunos252 - also RN:  `Connection` and `DatabaseClient` classes can now accept queries as parameters.

**Comment by brunos252** [comment]
@vpavicic 
Add support for passing parameters to openCypher (or just Cypher) queries

**Comment by vpavicic** [comment]
That's not very user-oriented... what can users now do because of this support? What kind of parameters?

**Comment by brunos252** [comment]
Well for instance UNWIND data and use it in a query. https://github.com/memgraph/gqlalchemy/pull/217/files#diff-63ff39fb53d411813d938ec712d5716caee4352d5d5d1e02b5955fad01486550 Is a good example

**Comment by vpavicic** [comment]
RN; Now you can pass values from Python variables as parameters in Cypher queries

**Pull request merged**
