### PR TITLE
Remove extra positional argument for `escape_value`

### PR DESCRIPTION
**Pull request by insectatorious**
`escape_value` doesn't accept two positional arguments, this change removes the extra boolean value.

### Description
Issue only occurs when using a `list` or `dict` type for the node's attribute.

There was an extra positional argument, this has been removed.

### Pull request type

Please delete options that are not relevant.

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring with functional or API changes
- [ ] Refactoring without functional or API changes
- [ ] Build or packaging related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete section if this PR doesn't resolve any issues. 

Closes (link to issue)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

### CODE REVIEW

**Review by katarinasupe — CHANGES_REQUESTED** [review]
Can you please add tests for these? I see they are missing so that we can confirm the change is good. For example, a simple test for list property in [/tests/ogm/test_properties.py](https://github.com/memgraph/gqlalchemy/blob/main/tests/ogm/test_properties.py) would be:

```
@pytest.mark.parametrize("database", ["neo4j", "memgraph"], indirect=True)
def test_list_property(database):
    class User(Node):
        my_list: list

    user = User(my_list=[1, 2, 3]).save(database)

    loaded_user = database.load_node(user)

    assert type(loaded_user) is User
    assert "my_list" in User.__fields__
    assert loaded_user.my_list == [1, 2, 3]
```

Similar for dict.

**Comment by wisedier** [comment]
I got the same issue. @insectatorious @katarinasupe Would you make some time to resolve this issue? If you don't, I'll send PR.

**Comment by katarinasupe** [comment]
Hi @wisedier :) Since @insectatorious was not responsive for quite some time, feel free to open a new PR and don't forget to add some basic tests. If help is needed, someone from the GQLAlchemy team can take over.

**Comment by wisedier** [comment]
@katarinasupe I also tried to handle dictionary type property with the below `Vote` model and modified `escape_value`, but it causes an exception I could not understand. Would you check it?

```python
# tests/ogm/test_properties.py
@pytest.mark.parametrize("database", ["neo4j", "memgraph"], indirect=True)
def test_dict_property(database):
    class Vote(Node):
        counts: dict

    counts = {
        "Emma": 3,
        "Liam": 1,
        "Olivia": 3,
        "Noah": 3,
        "Ava": 7,
    }
    vote = Vote(counts=counts).save(database)
    loaded_vote = database.load_node(vote)

    assert isinstance(loaded_vote, Vote)
    assert "counts" in Vote.__fields__
    for k, v in loaded_vote.counts.items():
        assert v == counts[k]

# gqalchemy/models.py
def escape_value(...):
    ...
    elif value_type == dict:
        return "{" + ", ".join(f"{key}: {self.escape_value(val)}" for key, val in value.items()) + "}"
        # return "{" + ", ".join(f"{val}: {self.escape_value(val, True)}" for key, val in value.items()) + "}" - original version
```

The test throw the below exception:
```
neo4j.exceptions.CypherTypeError: Property values can only be of primitive types or arrays thereof. Encountered: Map{Olivia -> Long(3), Liam -> Long(1), Emma -> Long(3), Ava -> Long(7), Noah -> Long(3)}.
```

**Comment by katarinasupe** [comment]
Hi @wisedier, I will have to check that - not sure about Neo4j errors, so I need to explore more. Let me know if you figure it out before I manage to check it out.

**Comment by katarinasupe** [comment]
@insectatorious, do you plan to continue working on this PR or @wisedier are you willing to open a new PR? We plan to release new version of GQLAlchemy soon including #235, so this can go with it if you manage to resolve it.

**Comment by insectatorious** [comment]
@katarinasupe apologies for going AWOL I should have clarified I was not going to be available after I submitted the PR. I can pick this up over the weekend but not today/tomorrow, please let me know if this is ok.

**Comment by katarinasupe** [comment]
@insectatorious fine by me 😄 Thanks for the response. I plan to release it by the end of the next week, so it would be awesome if you could make it by then 😄

**Comment by insectatorious** [comment]
@katarinasupe I've run into issues trying to run the tests on my local machine ([please see messages on Discord](https://discord.com/channels/842007348272169002/890969266600423504/1094246667387146302)). I've added two tests but I haven't been able to check that they work.

**Comment by katarinasupe** [comment]
Hi, @insectatorious, I added the comment on Discord, but I will add it here too. Can you run just:

` poetry run pytest ./tests/ogm/test_properties.py`

since you're working on tests there and let me know if the issue persists? We need to take deeper look into that, but for now, this might help to avoid import issues.

**Comment by insectatorious** [comment]
[As discussed on Discord](https://discord.com/channels/842007348272169002/890969266600423504/1094321085492772937), the `list` unit test is passing but the `dict` one is failing and it's not clear if this is because there are restrictions on the key-value types that are supported by memgraph or if there is a bug with how the query is generated. 

In summary, when trying to save a dict like `{"a": "1"}` we get a `DatabaseError` from `execute_and_fetch` in `gqlalchemy/connection.py:91`.
image

In the test `User` is defined as:

```python
    class User(Node):
        my_dict: dict
```
and `user = User(my_dict=expected_dict).save(database)` throws the error in the screenshot above.

**Comment by katarinasupe** [comment]
Adding a comment here too, for the visibility:
I tested this for a bit on Memgraph, and I concluded that this is the correct form of dict as a property:

```
CREATE (node:Node)
SET node.my_dict = {a: '1'}
RETURN node;
```

This is also a correct query:
```
CREATE (node:Node)
SET node.my_dict = {a: 1}
RETURN node;

```
This too:
```
CREATE (node:Node)
SET node.my_dict = {a: [1,2,3]}
RETURN node;
```

So, the **key has to be a string without quotes around it**, while the `value can be any supported data type in Memgraph`, as stated in the docs: https://memgraph.com/docs/memgraph/next/reference-guide/data-types

`Map    A mapping of string keys to values of any supported type.`

It is just confusing that keys are strings, but without quotes in this case, obviously.

For example, this is not a correct query:
```
CREATE (node:Node)
SET node.my_dict = {1: '1'}
RETURN node;
```

And this is not a correct query:
```
CREATE (node:Node)
SET node.my_dict = {"a": "1"}
RETURN node;
```

My conclusion would be that we have to be careful in GQLAlchemy when translating such property into a Cypher query, so there might be a bug on that side if the queries above are not working correctly.

**Comment by insectatorious** [comment]
Hi @katarinasupe just checking you're not waiting on anything from me to merge this. I can see the `status:ready` label but not really sure how that works interally.

**Comment by katarinasupe** [comment]
Hi @insectatorious, no worries, your PR is ready for merge, and our release master @brunos252 will merge it on Wednesday 😄 Thanks for asking!

**Review by brunos252 — APPROVED** [review]

**Pull request merged**
