### PR TITLE
Add regex operator

### LINKED ISSUE #267: [BUG] Missing Cypher operators
**Environment** 
* GQLAlchemy 1.4.1
* Python 3.9.2
* Debian 11.7
* Memgraph 2.9.0

**Describe the bug** 
Some Cypher operators are missing from GQLAlchemy implementation.

I need to use the "=~" operator for a pattern matching query but it's not declared in the enumeration :
https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/query_builders/declarative_base.py#L84

Sadly, it's not possible to build the query without the enum due to this line :
https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/query_builders/declarative_base.py#L184

**To Reproduce** 

Instead of pasting here a lot of my application code, please find below an unstested example adapted from https://memgraph.com/docs/cypher-manual/clauses/where#3-regular-expressions

1. Build a query using the string '=~' in place of the missing enum operator

`query = match().node(labels="Person", variable="n").where(item="n.name", operator="=~", literal=".*a$").return("n")`

2. Run it

`query.execute()`

3. It will raise that kind of exception

`[...]
File "/home/philippe/.local/share/virtualenvs/Engine-tgOo-fyU/lib/python3.9/site-packages/gqlalchemy/query_builders/declarative_base.py", line 950, in and_where
    self._query.append(AndWhereConditionPartialQuery(item=item, operator=operator, **kwargs))
  File "/home/philippe/.local/share/virtualenvs/Engine-tgOo-fyU/lib/python3.9/site-packages/gqlalchemy/query_builders/declarative_base.py", line 212, in __init__
    super().__init__(item=item, operator=operator, keyword=Where.AND, **kwargs)
  File "/home/philippe/.local/share/virtualenvs/Engine-tgOo-fyU/lib/python3.9/site-packages/gqlalchemy/query_builders/declarative_base.py", line 172, in __init__
    self.query = self._build_where_query(item=item, operator=operator, **kwargs)
  File "/home/philippe/.local/share/virtualenvs/Engine-tgOo-fyU/lib/python3.9/site-packages/gqlalchemy/query_builders/declarative_base.py", line 186, in _build_where_query
    raise GQLAlchemyOperatorTypeError(clause=self.type)
gqlalchemy.exceptions.GQLAlchemyOperatorTypeError
`

**Expected behavior**

A full support by GQLAlchemy of all Cypher operators (and all related syntax)

**Additional context** 

Patching the enum (declared at https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/query_builders/declarative_base.py#L84) allows to build and run properly a query containing a regex.

### PR DESCRIPTION
**Pull request by imilinovic**
### Description

Add regex operator (it already exists in Memgraph).

### Pull request type
closes #267 

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring with functional or API changes
- [ ] Refactoring without functional or API changes
- [ ] Build or packaging related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete section if this PR doesn't resolve any issues. 

Closes (link to issue)

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [gqlalchemy/docs](https://github.com/memgraph/gqlalchemy/tree/main/docs)

######################################

### CODE REVIEW

**Comment by katarinasupe** [comment]
@imilinovic We no longer use the develop branch for the release; everything goes directly to the main. Please rebase.
Why there are 96 changes? It's quite hard to review.

FYI, as discussed, this will be included in the next release (July 3rd). Work on Memgraph is a priority, so we can move the milestone due date if you can't make it.

**Review by antepusic — CHANGES_REQUESTED** [review]
I think there should be a test for this

**Comment by katarinasupe** [comment]
@antepusic isn't the test added by parametrizing the existing test?

**Review by katarinasupe — APPROVED** [review]

**Review by antepusic — APPROVED** [review]
@katarinasupe You're right, approved

**Review by as51340 — APPROVED** [review]

**Comment by katarinasupe** [comment]
@imilinovic  merge the latest main for tests to pass.
Once the tests pass, feel free to squash and merge.

**Pull request merged**
